### ISSUE TITLE
Rear Wheel Speed Senor Connected to invalid GPIO

### ISSUE THREAD

**Issue by lordnathan0** [BuckeyeCurrent/Rear-MCN-Breakout#9]
According to MCN code the only pins that can be used to measure Wheel Speed is either GPIO 26 or 19 
@sharrington93  is this correct?

According to the schematic "REAR_WSS" is connected to GP0

**Comment by lordnathan0** [comment]
NEVER MIND I WAS MISS READING THE DOCUMENTATION

**Comment by sharrington93** [comment]
@lordnathan0 I see you probably figured it out but correct to some degree. If it's GP0 that's GPIO 26 and an example of using that output is here: https://github.com/BuckeyeCurrent/MCN-Software/blob/Mid-Magic-CAN-Node/team_src/SensorCov.c#L97
